modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${displayName}"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/638111"
logoFile="icon.png"
authors="Grend, Mat0u5"
description='''A library all about color! Provides lots of color-related functionality for dependent mods.'''

[[modDependency]]
	modId="neoforge"
	type="required"
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[[modDependency]]
	modId="minecraft"
	type="required"
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[[mixins]]
	config="${modId}.mixins.json"